Repository 7-7-2/DDocker_FE, pull requests merged in 2024-05, with the labels that each got.

#199 Fix: footer icon match on page navigation
  src/components/common/FooterIcon.tsx
Labels: 🧞‍♂️ 완료, 🔌 기능구현

#225 Feat: set up CI/CD
  .github/workflows/deploy.yaml
Labels: 🧞‍♂️ 완료, 🔌 기능구현

#241 Feat: handleSubmitCommentByEnter
  src/components/common/Input.tsx
  src/components/post/PostInput.tsx
  src/types/types.ts
Labels: 🧞‍♂️ 완료, 🔌 기능구현

#242 Fix: deleteAccount Flow
  src/api/user.ts
  src/components/mypage/MyProfile.tsx
  src/components/start/SelectFavBrand.tsx
  src/constants/profile.ts
  src/hooks/MyPage/useHandleAuth.ts
Labels: 🔥 Fix, 🧞‍♂️ 완료

#253 Feat: integrate dev to main
  public/pwabuilder-sw.js
  src/components/common/SEOMeta.tsx
Labels: 🧞‍♂️ 완료

#255 Hotfix: upadte puppeteer script
  .gitignore
  .puppeteerrc.cjs
  package.json
Labels: 🔥 Fix

#259 Feat: replace hasamdong to tomntoms
  public/png/hasamdong.png
  public/png/tomntoms.png
  public/pwabuilder-sw.js
  src/constants/coffee.ts
  src/hooks/home/useGetPopularList.ts
  src/utils/convertBrandName.ts
  src/utils/getBrandPath.ts
Labels: 🧞‍♂️ 완료, 🔌 기능구현

#263 Fix: manifest.json
  public/manifest.json
  public/png/coffeepage.png
  public/png/feedpage.png
  public/png/homepage.png
  public/pwabuilder-sw.js
Labels: 🔥 Fix

#271 Fix: WeeklyPopualarItem
  src/components/home/WeeklyPopular.tsx
  src/components/home/WeeklyPopularItem.tsx
Labels: 🔥 Fix, 🧞‍♂️ 완료
