Repository 7-7-2/DDocker_FE, pull requests merged in 2024-06, with the labels that each got.

#286 Refactor: onTouchEnd => onClick
  src/components/coffee/LogInCTA.tsx
  src/components/common/Button.tsx
  src/components/common/CTA.tsx
  src/components/common/CoffeeOptionSelection.tsx
  src/components/common/FooterIcon.tsx
  src/components/common/Header.tsx
  src/components/common/HeaderCloseIcon.tsx
  src/components/common/HeaderIcon.tsx
  src/components/common/Icon.tsx
  src/components/common/ImgRegister.tsx
  src/components/common/Input.tsx
  src/components/common/ModalCTA.tsx
  src/components/common/SelectBox.tsx
  src/components/common/SelectBtn.tsx
  src/components/common/SelectOption.tsx
  src/components/common/Taps.tsx
  src/components/follow/FollowBtn.tsx
  src/components/home/CaffeineFilter.tsx
  src/components/home/CoffeeMenuSelection.tsx
  src/components/home/CoffeeSelection.tsx
  src/components/home/WaterIntake.tsx
  src/components/home/WaterPerCoffee.tsx
  src/components/mypage/MyProfile.tsx
  src/components/post/CafeDetail.tsx
  src/components/post/CafeDetailContent.tsx
  src/components/post/PostDetail.tsx
  src/components/post/PostRegister.tsx
  src/components/post/ReplyToPanel.tsx
  src/components/post/overlay/Option.tsx
  src/components/post/overlay/PostOwnerOption.tsx
  src/components/post/overlay/PublicOption.tsx
  src/components/posts/following/PostBody.tsx
  src/components/posts/following/PostCard.tsx
  src/components/posts/trend/DailyTrendCard.tsx
  src/components/posts/trend/PostsSortBy.tsx
  src/components/profile/FollowCount.tsx
  src/components/profile/PostsGrid.tsx
  src/components/report/ReportReason.tsx
  src/components/search/SearchBar.tsx
  src/components/start/BrandItem.tsx
  src/components/start/InitialForm.tsx
  src/components/start/SelectFavBrand.tsx
  src/components/start/SignIn.tsx
  src/components/support/CustomerCenter.tsx
  src/hooks/MyPage/useHandleAuth.ts
  src/hooks/useSelectBox.ts
  src/hooks/useSelectTap.tsx
  src/pages/Page-Error.tsx
  src/pages/Page-Follow.tsx
  src/pages/Page-Profile.tsx
  src/pages/Page-Report.tsx
  src/types/types.ts
Labels: 🔥 Fix, 🧞‍♂️ 완료

#295 Refactor: gzip
  package.json
  pnpm-lock.yaml
  src/components/common/CTA.tsx
  src/components/home/TodayCaffeineText.tsx
  src/pages/Page-Search.tsx
  vite.config.ts
Labels: 🧞‍♂️ 완료

#297 Fix: SEO metadata && mainimg to webp
  index.html
  package.json
  public/png/coffee_mainimg.webp
  public/pwabuilder-sw.js
  src/components/common/SEOMeta.tsx
  src/components/home/TodayCaffeineText.tsx
  src/constants/SEOData.ts
  vite.config.ts
Labels: 🔥 Fix

#298 Fix: dependency
  pnpm-lock.yaml
  src/components/start/SignIn.tsx
Labels: 🔥 Fix

#301 Fix: signIn nav error
  src/components/start/SignIn.tsx
  src/hooks/useGetUserInfo.ts
  src/pages/Page-Start.tsx
Labels: 🔥 Fix, 🧞‍♂️ 완료

#304 Fix: exclude signin/signup process from service worker caching
  public/pwabuilder-sw.js
Labels: 🔥 Fix

#306 Fix: signin component
  public/pwabuilder-sw.js
Labels: 🔥 Fix

#310 Fix: WaterPerCoffee & pwabuilder
  public/pwabuilder-sw.js
  src/components/home/WaterPerCoffee.tsx
Labels: 🔥 Fix, 🧞‍♂️ 완료
